# Generated by Django 5.1.4 on 2024-12-22 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fetched_on', models.DateField()),
                ('travel_class', models.CharField(choices=[('E', 'Economy'), ('N', 'Premium Economy'), ('B', 'Business'), ('F', 'First')], default='B')),
                ('trip_type', models.CharField(choices=[('RETURN', 'Return'), ('ONEWAY', 'Oneway')], default='RETURN')),
                ('is_archived', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='core.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stopovers', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.trip')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('origin', 'destination', 'travel_class', 'trip_type'), name='unique_flight'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('trip', 'month'), name='unique_offer'),
        ),
    ]
