# Generated by Django 5.1.4 on 2024-12-25 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_options_remove_city_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('trip', 'price', 'month')},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('destination', 'origin', 'travel_class', 'trip_type')},
        ),
        migrations.RemoveConstraint(
            model_name='offer',
            name='unique_offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
