# Generated by Django 5.1.4 on 2024-12-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_offer_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
