# Generated by Django 5.1.4 on 2025-01-06 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_offer_price_in_eur_offer_price_in_eur_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(default=None, null=True, on_delete=models.deletion.SET_NULL, related_name='city', to='core.country'),
        ),
    ]
