# Generated by Django 5.1.4 on 2025-01-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_country_remove_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='offer',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
