volumes:
  postgres_data:

services:
  app:
    build:
      context: src
    container_name: flightsearch
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=flightsearch.settings
      - PYTHONPATH=/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
