volumes:
  postgres_data:

services:
  app:
    build:
      context: src
    container_name: bestpricedflights
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: src
    command: celery -A bestpricedflights worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: src
    command: celery -A bestpricedflights beat --loglevel=info
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
