name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Start Docker Container
        run: |
          docker build -t bestpricedflights ./src
          docker run --network=host -d --name app --env-file .env.test -p 8000:8000 bestpricedflights

      - name: Run Migrations
        run: docker exec app django-admin migrate

      - name: Run Django Tests
        run: docker exec app django-admin test

      - name: Stop Docker Container
        if: always()
        run: docker stop app
